//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string CodeInCompany { get; set; }
        public int R { get; set; }
        public int G { get; set; }
        public int B { get; set; }
        public int CompanyId { get; set; }
        public double Price { get; set; }
        public string Description { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
